# Generated by Django 4.2.4 on 2023-10-29 08:35

from django.db import migrations


def update_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    for item in item_model.objects.all():
        if item.price <= 10:
            item.rarity = 'Rare'
            item.save()
        elif item.price <= 20:
            item.rarity = 'Very Rare'
            item.save()
        elif item.price <= 30:
            item.rarity = 'Extremely Rare'
            item.save()
        else:
            item.rarity = 'Mega Rare'
            item.save()


def reverse_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    for item in item_model.objects.all():
        item.rarity = 'empty'
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_item'),
    ]

    operations = [
        migrations.RunPython(update_rarity, reverse_code=reverse_rarity)
    ]
